apache/servicecomb-website

_pages/about-slides.md
_pages/cn/about-slides.md

Signed-off-by: Eric Lee <dagang.li@huawei.com>

added 6th live streaming materials

---

_users/develop-with-rest-template.md
_users/develop-with-rpc.md
_users/invoke-control.md
_users/use-service-contract.md

translate following part:
- Develop with Rest Template
- Develop with Transparent RPC
- Use Service Contract
- Invoke Control
fix JIRA issue SCB-110 at: https://issues.apache.org/jira/browse/SCB-110

translate developing consumer service document for servicecomb website

---

_developers/cn/submit-codes.md
_developers/submit-codes.md

fix SCB-105 at https://issues.apache.org/jira/browse/SCB-105

SCB-105 update new repository address for servicecomb website

---

_users/use-tls.md

fix SCB-115 at https://issues.apache.org/jira/browse/SCB-115.

SCB-115 document translation for website

---

_users/deployment.md

fix SCB-114 at https://issues.apache.org/jira/browse/SCB-114.

SCB-114 document translation for servicecomb website

---

_users/zuul.md

fix part of SCB-112 at https://issues.apache.org/jira/browse/SCB-112.
only zuul section of Edge Service was finished.

SCB-112 Edge Service document translation for servicecomb website

---

_users/nginx.md

document translation for edge service part: confd and nginx.
part of SCB-112.
SCB-112 is finished together with PR https://github.com/apache/incubator-servicecomb-website/pull/10.

SCB-112 edge service document translation

---

_users/cn/deployment.md

fix SCB-121.
add missing step 1 for run-mode document.

SCB-121 add missing paragraph header

---

README.md
_config.yml

include Apache disclaimer for website and update repo name.

include ASF disclaimer

---

_developers/setup-develop-environment.md
_developers/submit-codes.md

Translated setup develop environment and submit code pages.

SCB-142 translate developers pages

---

_users/Metrics.md
_users/cn/Metrics.md

output level for write file change from error to trace because this LogEvent is not a "log"

[SCB-148] update metrics md

---

_data/authors.yml
_posts/2018-01-10-howto-upgrade-to-zipkin-v2.md

This howto describes the changes between zipkin and zipkin2 and how Java
Chassis upgraded to zipkin2.

[SCB-172] add how to upgrade to zipkin2 post

---

_data/navigation.yml
_users/cn/metrics-in-1.0.0-m1.md
_users/cn/metrics-integration-with-prometheus-in-1.0.0-m1.md
_users/cn/metrics-write-file-extension-and-sample-in-1.0.0-m1.md
_users/metrics-in-1.0.0-m1.md
_users/metrics-integration-with-prometheus-in-1.0.0-m1.md

add en version and sync cn version

[SCB-132] Metrics MD

---

_data/navigation.yml

Signed-off-by: Eric Lee <dagang.li@huawei.com>

SCB-273 proper indent in yaml

---

_users/cn/dynamic-config.md
_users/dynamic-config.md

[SCB-210] update document for apollo configuration item

---

_data/navigation.yml
_users/cn/metrics-integration-with-prometheus-in-1.0.0-m1.md

Signed-off-by: WangQilin <qilin.wang@huawei.com>

change "普罗米修斯" to "prometheus" in chinese metric docs

---

_config.yml
_data/navigation.yml
_release/cn/java_chassis_binaries.md
_release/cn/java_chassis_releaseNotes.md
_release/cn/release.md
_release/cn/saga_binaries.md
_release/cn/saga_releaseNotes.md
_release/cn/service_center_binaries.md
_release/cn/service_center_releaseNotes.md
_release/java_chassis_binaries.md
_release/java_chassis_releaseNotes.md
_release/release.md
_release/saga_binaries.md
_release/saga_releaseNotes.md
_release/service_center_binaries.md
_release/service_center_releaseNotes.md

Preview : https://asifdxtreme.github.io/incubator-servicecomb-website/release/  (Currently the preview doesn't work for Chinese locale, please check it in English Version)

Add Download Section in the website

---

_posts/cn/2018-04-04-config-center-integration.md

SCB-460 add blog to introduce config-center integration in servicecomb

---

_data/navigation.yml
_users/cn/edge-in-1.0.0-m1.md

add edge cn doc

---

_data/navigation.yml
_users/edge-in-1.0.0-m1.md

add edge en doc

---

_users/cn/metrics-in-1.0.0-m1.md
_users/cn/metrics-integration-with-prometheus-in-1.0.0-m1.md
_users/edge-in-1.0.0-m1.md
_users/metrics-in-1.0.0-m1.md
_users/metrics-integration-with-prometheus-in-1.0.0-m1.md

Fix some incorrect style

---

_data/navigation.yml
_developers/cn/release_guide.md
_developers/release_guide.md

Preview :  https://asifdxtreme.github.io/incubator-servicecomb-website/developers/release-guide/

Add the Release guide for ServiceComb

---

_users/cn/setup-environment.md
_users/setup-environment.md

add how to deploy service center in cluster mode

add how to deploy service center in cluster mode

---

_posts/cn/2018-04-13-build-java-chassis-microservices-using-gradle.md

Signed-off-by: Eric Lee <dagang.li@huawei.com>

SCB-457 show how to use gradle with java chassis

---

_faqs/cn/faq.md

fix faq mistakes

---

_users/cn/setup-environment.md
_users/setup-environment.md

add service center m1 fix method under Linux

add service center m1 fix method under Linux

---

_faqs/cn/faq.md

add Q&A about @ApiOperation

---

README.md

[SCB-519] Correct chapter 'How to run the site locally' of REAME.md
Signed-off-by: linzhinan <linzhinan@huawei.com>

[SCB-519] Correct chapter 'How to run the site locally' of REAME.md

---

_faqs/cn/faq.md
_users/cn/develop-with-jax-rs.md
_users/cn/develop-with-springboot-starter.md
_users/cn/develop-with-springmvc.md
_users/cn/develop-with-transparent-rpc.md
_users/develop-with-jax-rs.md
_users/develop-with-springboot-starter.md
_users/develop-with-springmvc.md
_users/develop-with-transparent-rpc.md

在编程模型文档中增加注意事项说明，并且修复FAQ中这方面错误的说法。

Add Notes for providers and fix FAQ mistakes

---

_developers/cn/release_guide.md
_developers/release_guide.md

Translate release guide to Chinese, also fixed a minor issue in saga release step.

[SCB-528] Translate release guide to Chinese

---

_release/cn/saga_downloads.md

SCB-554 translate doc 'saga_downloads' for website

---

_release/cn/java_chassis_downloads.md

SCB-553 translate doc 'java_chassis_downloads' for website

---

_release/cn/service_center_downloads.md

SCB-552 translate doc 'service_center_downloads' for website

---

_data/navigation.yml
_posts/2018-05-23-apache-servicecomb-incubating-day.md
_posts/cn/2018-05-23-apache-servicecomb-incubating-day.md

Signed-off-by: linzhinan linzhinan@huawei.com

[SCB-606] Add blog about updated Apache ServiceComb (incubating) Day on website

---

_data/navigation.yml
_developers/cn/contributing.md
_developers/contributing.md

fix contributing url and translate cn

---

_posts/cn/2018-06-06-how-to-grow-up-to-be-an-apache-committer.md

add how-to-grow-up-to-be-an-apache-committer blog

---

_data/navigation.yml

fix release-validation-guide en url

---

_users/cn/service-configurations.md
_users/service-configurations.md

The wrong format leads to a problem with web typography.
Signed-off-by: MabinGo <bin.ma@huawei.com>

Fix web page wrong format

---

_developers/cn/team.md
_developers/team.md

add jyseanl in team

---

_data/authors.yml
_posts/2018-06-28-apache-servicecomb-incubating-day-report.md

Signed-off-by: Wang Kirin <qilin.wang@huawei.com>

add LC3 servicecomb workshop report

---

_users/cn/setup-environment.md

Change the links of service center from 1.0.0-m1 to 1.0.0-m2

Update links to service-center-1.0.0-m2

---

_users/setup-environment.md

Change the links of service center from 1.0.0-m1 to 1.0.0-m2

Update service center links

---

_data/authors.yml
_posts/cn/2018-07-21-consul-servicemesh.md

Add the blog about Consul Service Mesh and the author info.

Add the blog to introduce Consul Service Mesh

---

_data/navigation.yml
script/bootstrap
script/deploy
script/release
script/start-server

add gitbook cn version of user guide 

---

_posts/cn/2018-8-13-1.0.0-release-note.md

Signed-off-by: Wang Kirin <qilin.wang@huawei.com>

add 1.0.0-release-note

---

_pages/cn/home.md
_posts/cn/2018-8-13-1.0.0-release-note.md

Signed-off-by: Wang Kirin <qilin.wang@huawei.com>

edit homepage latest news & add github link

---

_data/navigation.yml

preview at https://imlidian.github.io/users/

update _data/navigation.yml for user guide

---

_posts/cn/2018-11-20-opensource-project-is-not-so-far-away.md

additional content for opensource-project-is-not-so-far-away.md

---

_data/navigation.yml
_developers/cn/becomming-a-committer.md
_developers/cn/developer-guide.md
_developers/developer-guide.md
_pages/cn/home.md
_pages/home.md

Signed-off-by: MabinGo <bin.ma@huawei.com>

 Update and fix some pages base on the latest information

---

2019-01-23-customized-tracing-with-servicecomb.md

add customized-tracing-with-servicecomb of user guide

add customized-tracing-with-servicecomb of user guide

---

_developers/cn/team.md
_developers/team.md

 rename Contributor name

---

_docs/cn/distributed-tracing.md
_docs/cn/flow-control.md
_docs/cn/load-balance.md
_docs/cn/service-management.md
_docs/distributed-tracing.md
_docs/flow-control.md
_docs/load-balance.md
_docs/service-management.md

SCB-1390 add springboot maven plugin 2.x support -Dspring-boot.run.jvmArguments @WillemJiang

SCB-1390 add springboot maven plugin 2.x support 

---

_users/cn/service-configurations.md
_users/service-configurations.md

SCB-1413 update the outdated loadbalance docs links

---

_data/navigation.yml
_developers/cn/developer-guide.md
_release/cn/release.md
_release/cn/toolkit_downloads.md
_release/cn/toolkit_releaseNotes.md
_release/toolkit_downloads.md
_release/toolkit_releaseNotes.md

Update ServiceComb Toolkit 0.1.0 Release information

Update ServiceComb Toolkit 0.1.0 Release information

---

_pages/cn/home.md
_pages/home.md
_release/cn/release.md
_release/release.md

Add the toolkit release 0.1.0 information and reorganize Latest News

Update the home page

---

_pages/cn/home.md
_pages/home.md
_release/cn/release.md
_release/cn/toolkit_downloads.md
_release/cn/toolkit_releaseNotes.md
_release/release.md
_release/toolkit_downloads.md
_release/toolkit_releaseNotes.md

Update Toolkit 0.2.0 Release information

Update Toolkit 0.2.0 Release information

---

_pages/cn/home.md
_pages/home.md

@WillemJiang @MabinGo 
2 of home page's features' URL link have been broken. I have fixed them, and have added another link for the the other mesh feature.

fix home page features row's broken links

---

_data/navigation.yml
_includes/head/custom.html
_pages/cn/home.md
_pages/cn/summer2020.html
_pages/home.md
_pages/summer2020.html

add summer2020 page and change fonts.cat.net for speeding visiting @WillemJiang

Summer2020

---

_pages/cn/home.md

fix a url typo

---

_pages/cn/summer2020.md

@WillemJiang add summer2020 projects license claim.

 add summer 2020 license
